### ISSUE TITLE
table header ripple problem

### ISSUE THREAD

**Issue by userquin** [OWOX/brainy-table#14]
I have a table with 4 columns, but the ripple in third column is not covering the full column header width (ripple in columns 1 and 2 are working correctly, column 4 is not sortable): 

```html
<brainy-table-column flex="0" sort-by=...
<brainy-table-column flex="1" sort-by=...
<brainy-table-column flex="2" sort-by=...
<brainy-table-column flex="0" name=...
```
and its styles: 

```css
brainy-tr brainy-th:first-of-type, brainy-tr brainy-td:first-of-type {
    padding-left: 32px;
    flex-basis: 70px !important;
}
brainy-tr brainy-td:last-of-type, brainy-tr brainy-th:last-of-type {
    padding-left: 24px;
    flex-basis: 70px !important;
}
brainy-tr brainy-th:nth-child(2), brainy-tr brainy-td:nth-child(2) {
    padding-left: 32px;
}
```
