### ISSUE TITLE
font color in header changes after sorting.

### ISSUE THREAD

**Issue by aneesshameed** [OWOX/brainy-table#21]
```css
brainy-th {
            font-weight: bold;
            color: #fff;
            background-color: var(--paper-light-blue-500);
    }
```
I gave styling to table header. But, after I enabled sorting on columns and when a user sorts the table, font color gets reverted to black.
